apiVersion: v1
kind: Secret
metadata:
  name: datadog-agent
  labels:
    app: oficina-cardozo-osservice-api
type: Opaque
data:
  api_key: MjJjMWZlZjI4MWY2MzVlOGM3OWVmOGVhMDUyODk1Njg=
  app_key: NGM4Zjc0OWNiNTA5M2I3YjgzNzYzMDBmZmJhZTZjYjk0MzFiZDMyNQ== # valor convertido para base64