apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  labels:
    app: oficina-cardozo-osservice-api
type: Opaque
data:
  # api_key deve ser base64
    api_key: MjJjMWZlZjI4MWY2MzVlOGM3OWVmOGVhMDUyODk1Njg=