apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-cardozo-osservice-api
  labels:
    app: oficina-cardozo-osservice-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oficina-cardozo-osservice-api
  template:
    metadata:
      labels:
        app: oficina-cardozo-osservice-api
      annotations:
        ad.datadoghq.com/api.logs: '[{"source":"csharp","service":"oficina-cardozo-osservice-api"}]'
    spec:
      containers:
        - name: api
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secret
                  key: api_key
            - name: DATADOG_API_KEY_AGENT
              valueFrom:
                secretKeyRef:
                  name: datadog-agent
                  key: api-key
            - name: DATADOG_SITE
              value: us5.datadoghq.com
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: osservice-db-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: osservice-db-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: osservice-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osservice-db-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          image: marciocardozodev/oficinacardozo-osservice-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
