apiVersion: v1
kind: Secret
metadata:
  name: osservice-db-secret
  namespace: osservice-prod
  labels:
    app: oficina-cardozo-osservice-api
type: Opaque
data:
  DB_HOST: <base64_do_endpoint>
  DB_NAME: <base64_do_nome_do_banco>
  DB_USER: <base64_do_usuario>
  DB_PASSWORD: <base64_da_senha>
