apiVersion: v1
kind: Service
metadata:
  name: oficina-cardozo-osservice-api
  labels:
    app: oficina-cardozo-osservice-api
spec:
  selector:
    app: oficina-cardozo-osservice-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
